### ISSUE TITLE
垃圾！不支持点击Item滑动到中心位置

### ISSUE THREAD

**Issue by q88qaz** [ListerChen/RecyclerViewDemo#1]
垃圾！不支持点击Item滑动到中心位置
垃圾！不支持点击Item滑动到中心位置
垃圾！不支持点击Item滑动到中心位置
垃圾！不支持点击Item滑动到中心位置
垃圾！不支持点击Item滑动到中心位置
自定义还各种bug
垃圾！不支持点击Item滑动到中心位置
垃圾！不支持点击Item滑动到中心位置
垃圾！不支持点击Item滑动到中心位置
垃圾！不支持点击Item滑动到中心位置

**Comment by ListerChen** [comment]
一个Demo看把你急的，打了这么多字也不明白你说的啥，在哪儿高就啊大神？
还有你说的这些功能简单的很，几行代码就能实现，不知道你BB啥，你不会做不出来吧？
